version: "3.7"

services:
  http-app:
    build:
      context: .
    ports:
      - "5000"
    volumes:
      - ./:/server
    command: "gunicorn --bind 0.0.0.0:5000 wsgi:app"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - http-app
    ports:
      - "80:80"